services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_APP_NAME: Fylmico
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
